version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14-stretch
    working_directory: ~/bitbucket-role

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install dependencies
          command: |
            sudo pip install -r .circleci/requirements.txt
      - run:
          name: run tests
          command: |
            molecule test --driver docker
